openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: local-host
  url: http://localhost:8090/v1
security:
- {}
tags:
- description: not yet ready
  name: awdadw
paths:
  /awdadw:
    post:
      operationId: createawdadw
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/awdadw'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/awdadw'
          description: successful operation
      summary: Creates the data
      tags:
      - awdadw
      x-eov-operation-handler: controllers/AwdadwController
  /awdadw/{awdadwId}:
    delete:
      operationId: deleteawdadw
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: awdadwId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - awdadw
      x-eov-operation-handler: controllers/AwdadwController
    get:
      operationId: getawdadw
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: awdadwId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/awdadw'
          description: successful operation
      summary: Get the element
      tags:
      - awdadw
      x-eov-operation-handler: controllers/AwdadwController
    put:
      operationId: updateawdadw
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: awdadwId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/awdadw'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/awdadw'
          description: successful operation
      summary: Updates the element
      tags:
      - awdadw
      x-eov-operation-handler: controllers/AwdadwController
  /awdadw/getAll:
    get:
      operationId: getAllawdadw
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/awdadw'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - awdadw
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/AwdadwController
components:
  schemas:
    awdadw:
      example:
        tyest: tyest
        _id: _id
      properties:
        _id:
          type: string
        tyest:
          type: string
      required:
      - tyest
      type: object
